# Generated by Django 3.1.7 on 2021-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210313_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduser',
            name='times_queried',
            field=models.PositiveIntegerField(default=0, verbose_name='Num. of times queried'),
        ),
    ]
